version: "3"
services:
  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: "galaxyhub-bc-redis"
    volumes:
      - ./.docker/redis:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
  mariadb:
    image: mariadb:10.10
    container_name: "galaxyhub-bc-mariadb"
    restart: always
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: develop
    ports:
      - 3306:3306
